#!/bin/bash
# Quick Railway Backend Variable Checker
# This helps verify your Railway environment variables are set correctly

echo "🔍 Railway Backend Variable Checker"
echo "====================================="
echo ""
echo "📋 Required Variables for Backend:"
echo ""
echo "✓ DB_HOST should reference: \${{MySQL.MYSQLHOST}}"
echo "✓ DB_PORT should reference: \${{MySQL.MYSQLPORT}}"
echo "✓ DB_USER should reference: \${{MySQL.MYSQLUSER}}"
echo "✓ DB_PASSWORD should reference: \${{MySQL.MYSQLPASSWORD}}"
echo "✓ DB_NAME should be: dairy_db"
echo ""
echo "---"
echo ""
echo "🎯 How to Add These in Railway:"
echo ""
echo "1. Go to: https://railway.app/dashboard"
echo "2. Click your Backend service (dairy-management-api)"
echo "3. Go to 'Variables' tab"
echo "4. Add each variable with the value shown above"
echo "5. Backend will auto-redeploy"
echo ""
echo "---"
echo ""
echo "📊 Your MySQL Service Variables (from Railway):"
echo ""
echo "MYSQLHOST: mysql-ur4r.railway.internal"
echo "MYSQLPORT: 3306"
echo "MYSQLUSER: root"
echo "MYSQLPASSWORD: GqsGfqozHbDVdoeqEWqaQfiCdqJaJopt"
echo "MYSQLDATABASE: railway (but we use dairy_db)"
echo ""
echo "---"
echo ""
echo "🔧 Backend Needs These Mapped:"
echo ""
echo "DB_HOST=${{MySQL.MYSQLHOST}}"
echo "DB_PORT=${{MySQL.MYSQLPORT}}"
echo "DB_USER=${{MySQL.MYSQLUSER}}"
echo "DB_PASSWORD=${{MySQL.MYSQLPASSWORD}}"
echo "DB_NAME=dairy_db"
echo ""
echo "---"
echo ""
echo "✅ After Adding Variables:"
echo ""
echo "1. Wait ~2 minutes for redeploy"
echo "2. Check logs for: '✅ Database connected successfully'"
echo "3. Test: curl https://dairy-management-api-production.up.railway.app/health"
echo "4. Login from frontend with admin@dairysystem.com / admin123"
echo ""
echo "🎉 That's it! The 500 error will be gone!"
